name: Train ML Models with MLflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow scikit-learn pandas numpy

      - name: Check dataset file
        run: |
          if [ ! -f "CAR DETAILS FROM CAR DEKHO_preprocessed.csv" ]; then
            echo "Dataset not found!"
            exit 1
          fi

      - name: Run ML training
        run: python modelling.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
